project:
  type: website
  output-dir: _site

website:
  title: "Using PLIDA: larger-than-memory data in R"
  navbar:
    left:
      - href: index.qmd
        text: Overview
      - href: 00-setup.qmd
        text: Setup
      - href: 01-reading-storing.qmd
        text: 1. Reading & storing
      - href: 02-data-manipulation.qmd
        text: 2. Data manipulation
      - href: 03-joins.qmd
        text: 3. Joins
      - href: 04-window-functions.qmd
        text: 4. Window functions
      - text: "---"
      - text: Benchmarks
        menu:
          - href: A1-reading-storing-benchmarks.qmd
            text: "A1: Reading & storing"
          - href: A2-data-manipulation-benchmarks.qmd
            text: "A2: Data manipulation"
          - href: A3-join-benchmarks.qmd
            text: "A3: Joins"
          - href: A4-window-function-benchmarks.qmd
            text: "A4: Window functions"
      - text: "---"
      - text: Case studies
        menu:
          - href: cs01-earnings.qmd
            text: "CS1: How much do people earn?"
          - href: cs02-health-services.qmd
            text: "CS2: Who uses health services?"
          - href: cs03-csv-to-chart.qmd
            text: "CS3: CSV to chart in 20 minutes"
          - href: cs04-job-switching.qmd
            text: "CS4: Job switching and health shocks"

format:
  html:
    theme: [cosmo, custom.scss]
    toc: true
    code-fold: show
    code-tools: true
    df-print: paged
    embed-resources: true
    self-contained-math: true

execute:
  freeze: auto
  warning: false
  message: false
